### ISSUE TITLE
tp to me?

### ISSUE THREAD

**Issue by MemLiveOn** [MintLily/VRChat-TeleporterVR#3]
Ok, so I use Munchen, which has a teleport function. But it doesn't have a teleport to me function. And I swear I remember seeing something somewhere in teleportervr that allows one to tp someone else to me. But I can't seem to be able to find it. If it isn't in, can it be suggested? Or, if not, can you suggest another plugin that allows that?

**Comment by MintLily** [comment]
No, it's not in this project; and probably never will. That would require the use of an external server which I will not do.
And I won't be helping with any mod compatibility not from the VRChat Modding Group. 

And I'll just leave [this here](https://github.com/knah/VRCMods/blob/master/Malicious-Mods.md).
