### ISSUE TITLE
[BUG] Major performance loss until quick menu is open at least once

### ISSUE THREAD

**Issue by Provini** [MintLily/VRChat-TeleporterVR#4]
Minor issue since all you need to do is open your quick menu and it's fine the entire time you're on for that game session, but worth reporting anyways.

In my home world, I drop to 60 frames but after opening and closing my menu, I'm back up to 90.

**Comment by MintLily** [comment]
Should be fixed in version [4.10.3](https://github.com/MintLily/VRChat-TeleporterVR/releases/tag/4.10.3)
