### ISSUE TITLE
Risky Function Toggle

### ISSUE THREAD

**Issue by Soutemumb** [MintLily/VRChat-TeleporterVR#5]
Cannot use this on Game instances
Please fix?

**Comment by TanukiPenny** [comment]
Depending on the world ur not supposed to be able to use it in game and club worlds to prevent cheating/invasion of privacy

**Comment by Soutemumb** [comment]
Mods are already against the rules on VRChat though, I want to be able to use risky functions in game instances.

**Comment by MintLily** [comment]
And? We aim to make VRChat slightly more enjoyable to be in with features the devs may or may not implement. We do not want to ruin the experience for others playing minigames. (We do not want there to be any unfair advantage over others trying to have a good time.)
So, I am **not** changing this system.
